import { defineModuleApi } from "@dashlane/framework-contracts";
import {
  GetIsLastAdminForItemQuery,
  GetPermissionForItemQuery,
  GetPermissionForItemsQuery,
  GetSharedAccessForItemIdsQuery,
  GetSharedAccessQuery,
  GetSharedItemForIdQuery,
  GetSharedItemsForItemIdsQuery,
  GetSharedItemsQuery,
  GetSharingStatusForItemQuery,
  GetSharingStatusForItemsQuery,
  GetSharingTeamLoginsQuery,
  GetUserSharedVaultItemsQuery,
  IsSharingAllowedQuery,
  SharedAccessForItemQuery,
  SharedItemsIdsQuery,
  ShareItemsErrorsQuery,
  SharingEnabledQuery,
} from "./queries";
import {
  RefuseSharedItemBeforeDeletionCommand,
  RefuseSharedItemCommand,
  RemoteControlSharedItemsCommand,
  RevokeSharedItemCommand,
  ShareItemsCommand,
  UpdateSharedItemContentCommand,
  UpdateSharedItemPermissionCommand,
} from ".";
export const sharingItemsApi = defineModuleApi({
  name: "sharingItems" as const,
  commands: {
    updateSharedItemPermission: UpdateSharedItemPermissionCommand,
    updateSharedItemContent: UpdateSharedItemContentCommand,
    revokeSharedItem: RevokeSharedItemCommand,
    refuseSharedItem: RefuseSharedItemCommand,
    refuseSharedItemBeforeDeletion: RefuseSharedItemBeforeDeletionCommand,
    remoteControlSharedItems: RemoteControlSharedItemsCommand,
    shareItems: ShareItemsCommand,
  },
  events: {},
  queries: {
    getSharedAccess: GetSharedAccessQuery,
    getSharedAccessForItemIds: GetSharedAccessForItemIdsQuery,
    getSharedItems: GetSharedItemsQuery,
    getSharedItemForId: GetSharedItemForIdQuery,
    isSharingAllowed: IsSharingAllowedQuery,
    getSharingTeamLogins: GetSharingTeamLoginsQuery,
    sharingEnabled: SharingEnabledQuery,
    getSharedItemsForItemIds: GetSharedItemsForItemIdsQuery,
    getSharingStatusForItem: GetSharingStatusForItemQuery,
    getSharingStatusForItems: GetSharingStatusForItemsQuery,
    getPermissionForItem: GetPermissionForItemQuery,
    getPermissionForItems: GetPermissionForItemsQuery,
    getIsLastAdminForItem: GetIsLastAdminForItemQuery,
    sharedAccessForItem: SharedAccessForItemQuery,
    getUserSharedVaultItems: GetUserSharedVaultItemsQuery,
    sharedItemsIds: SharedItemsIdsQuery,
    shareItemsErrors: ShareItemsErrorsQuery,
  },
});
