import { PasswordHistoryItemType, PasswordHistoryItemView, } from '@dashlane/communication';
export const passwordHistoryItems: PasswordHistoryItemView[] = [
    {
        primaryInfo: 'live.com',
        secondaryInfo: 'myAccountName',
        password: '12345!!!',
        timestamp: 1418555912,
        sharingStatus: {
            isShared: false,
        },
        type: PasswordHistoryItemType.Credential,
        credentialId: '42',
        id: '187654DEF',
        icons: {
            backgroundColor: 'FDFDFD',
            mainColor: '00004',
            urls: {
                '46x30@2x': '*****',
                '118x98@2x': '*****',
                '160x106@2x': '*****',
            },
        },
        isProtected: false,
        domain: 'live.com',
    },
    {
        primaryInfo: 'airbnb.com',
        password: 'js?j3hEER0!fdhah',
        timestamp: 1528778916,
        type: PasswordHistoryItemType.Generated,
        id: 'DJ584AE32',
    },
    {
        primaryInfo: 'google.com',
        secondaryInfo: 'lalala@gmail.com',
        password: 'lousyPassword',
        timestamp: 1618778916,
        sharingStatus: {
            isShared: false,
        },
        type: PasswordHistoryItemType.Credential,
        credentialId: '42',
        id: '987654ABC',
        icons: {
            backgroundColor: 'FDFDFD',
            mainColor: '00004',
            urls: {
                '46x30@2x': '*****',
                '118x98@2x': '*****',
                '160x106@2x': '*****',
            },
        },
        isProtected: false,
        domain: 'google.com',
    },
    {
        primaryInfo: 'acer.com',
        secondaryInfo: 'danielle@yahoo.com',
        password: 'pa$$w0rd',
        timestamp: 1628778916,
        sharingStatus: {
            isShared: false,
        },
        type: PasswordHistoryItemType.Credential,
        credentialId: '42',
        id: '123456ABC',
        icons: {
            backgroundColor: 'FDFDFD',
            mainColor: '00004',
            urls: {
                '46x30@2x': '*****',
                '118x98@2x': '*****',
                '160x106@2x': '*****',
            },
        },
        isProtected: false,
        domain: 'acer.com',
    },
    {
        primaryInfo: 'websitewithouticon.com',
        secondaryInfo: 'myLogin',
        password: 'passw0rd',
        timestamp: 1628778801,
        sharingStatus: {
            isShared: false,
        },
        type: PasswordHistoryItemType.Credential,
        credentialId: '42',
        id: '228676ABF',
        isProtected: false,
        icons: {
            backgroundColor: 'FDFDFD',
            mainColor: '00004',
            urls: {
                '46x30@2x': '*****',
                '118x98@2x': '*****',
                '160x106@2x': '*****',
            },
        },
        domain: 'websitewithouticon.com',
    },
    {
        primaryInfo: 'Generated in Dashlane',
        password: '47shS3IEL$??hds!9',
        timestamp: 1628978916,
        type: PasswordHistoryItemType.Generated,
        id: 'L9885A0OL',
    },
    {
        primaryInfo: 'acer.com',
        secondaryInfo: 'danielle@yahoo.com',
        password: 'pa$$w0rdNew',
        timestamp: 1630079990,
        sharingStatus: {
            isShared: false,
        },
        type: PasswordHistoryItemType.Credential,
        credentialId: '42',
        id: '123456DEF',
        icons: {
            backgroundColor: 'FDFDFD',
            mainColor: '00004',
            urls: {
                '46x30@2x': '*****',
                '118x98@2x': '*****',
                '160x106@2x': '*****',
            },
        },
        isProtected: false,
        domain: 'acer.com',
    },
    {
        primaryInfo: 'twitter.com',
        secondaryInfo: '',
        password: 'mypassword',
        timestamp: 1630943990,
        sharingStatus: {
            isShared: false,
        },
        type: PasswordHistoryItemType.Credential,
        credentialId: '42',
        id: '847102ERF',
        icons: {
            backgroundColor: 'FDFDFD',
            mainColor: '00004',
            urls: {
                '46x30@2x': '*****',
                '118x98@2x': '*****',
                '160x106@2x': '*****',
            },
        },
        isProtected: false,
        domain: 'twitter.com',
    },
    {
        primaryInfo: 'acer.com',
        secondaryInfo: 'danielle@yahoo.com',
        password: 'pa$$w0rdNewest!',
        timestamp: 1630979990,
        sharingStatus: {
            isShared: false,
        },
        type: PasswordHistoryItemType.Credential,
        credentialId: '42',
        id: '123456GHI',
        icons: {
            backgroundColor: 'FDFDFD',
            mainColor: '00004',
            urls: {
                '46x30@2x': '*****',
                '118x98@2x': '*****',
                '160x106@2x': '*****',
            },
        },
        isProtected: false,
        domain: 'acer.com',
    },
];
