const importedVariables: any = {};
const importedColorVariables: any = {};
const styleVars = {
    bkgGrey: '',
    bkgGreyDarker: '',
    bkgGreyDarkest: '',
    bkgGreyLighter: '',
    bkgTealDark: '',
    bkgTealMed: '',
    black20percent: '',
    black25percent: '',
    black60percent: '',
    white75percent: '',
    callToAction: '',
    fontfamilyMonospace: '',
    fontfamilyTac: '',
    fontfamilyWebapp: '',
    textBlack: '',
    textGreen: '',
    textGrey: '',
    textGreyDark: '',
    textGreyDarker: '',
    textGreyLighter: '',
    textGreyLightest: '',
    textRed: '',
    textTeal: '',
    webappAccentTeal: '',
    webappActiveLink: '',
    webappBackgroundGreyDarker: '',
    webappBackgroundOk: '',
    webappCredentialLogoBorder: '',
    webappTextBlack: '',
    webappTextLightgrey: '',
    bkgWebappAccountCreationHeader: '',
    backgroundGrey: '',
    black: '',
    blueberryBlue: '',
    blueberryBlueDark1: '',
    blueberryBlueDark2: '',
    blueberryBlueDark3: '',
    blueberryBlueDark4: '',
    blueberryBlueDark5: '',
    blueberryBlueLight1: '',
    blueberryBlueLight2: '',
    blueberryBlueLight3: '',
    blueberryBlueLight4: '',
    blueberryBlueLight5: '',
    cobaltYellow: '',
    cobaltYellowDark1: '',
    cobaltYellowDark2: '',
    cobaltYellowLight1: '',
    cobaltYellowLight2: '',
    darkGrey: '',
    deepMagenta: '',
    deepMagentaDark1: '',
    deepMagentaDark2: '',
    deepMagentaDark3: '',
    deepMagentaDark4: '',
    deepMagentaDark5: '',
    deepMagentaLight1: '',
    deepMagentaLight2: '',
    deepMagentaLight3: '',
    deepMagentaLight4: '',
    deepMagentaLight5: '',
    grey: '',
    highlightGrey: '',
    intenseOrange: '',
    intenseOrangeDark1: '',
    intenseOrangeDark2: '',
    intenseOrangeDark3: '',
    intenseOrangeDark4: '',
    intenseOrangeDark5: '',
    intenseOrangeLight1: '',
    intenseOrangeLight2: '',
    intenseOrangeLight3: '',
    intenseOrangeLight4: '',
    intenseOrangeLight5: '',
    lightGrey: '',
    skyBlue: '',
    skyBlueDark1: '',
    skyBlueDark2: '',
    skyBlueDark3: '',
    skyBlueDark4: '',
    skyBlueDark5: '',
    skyBlueLight1: '',
    skyBlueLight2: '',
    skyBlueLight3: '',
    skyBlueLight4: '',
    skyBlueLight5: '',
    teal: '',
    tealDark1: '',
    tealDark1Accent: '',
    tealDark2: '',
    tealDark3: '',
    tealDark4: '',
    tealDark5: '',
    tealLight1: '',
    tealLight2: '',
    tealLight3: '',
    tealLight4: '',
    tealLight5: '',
    vibrantGreen: '',
    vibrantGreenDark1: '',
    vibrantGreenDark2: '',
    vibrantGreenDark3: '',
    vibrantGreenDark4: '',
    vibrantGreenDark5: '',
    vibrantGreenLight1: '',
    vibrantGreenLight2: '',
    vibrantGreenLight3: '',
    vibrantGreenLight4: '',
    vibrantGreenLight5: '',
    warningRed: '',
    warningRedDark1: '',
    warningRedDark2: '',
    warningRedLight1: '',
    warningRedLight2: '',
    white: '',
};
Object.keys(importedVariables)
    .filter((name) => name.startsWith('--dashlane-'))
    .forEach((name) => {
    const transmuted = name
        .replace(/^--dashlane-/, '')
        .replace(/-[a-z0-9]/g, (s) => s.substr(1).toUpperCase());
    if (transmuted in styleVars) {
        styleVars[transmuted] = importedVariables[name];
    }
});
Object.keys(importedColorVariables).forEach((name) => {
    const transmuted = name
        .replace(/^--/, '')
        .replace(/-[a-z0-9]/g, (s) => s.substr(1).toUpperCase());
    if (transmuted in styleVars) {
        styleVars[transmuted] = importedColorVariables[name];
    }
});
export default styleVars;
