import { DEFAULT_FLEXIBLE_ARGON2D_DERIVATION_CONFIG, DEFAULT_FLEXIBLE_PBKDF2_DERIVATION_CONFIG, DEFAULT_NODERIVATION_CONFIG, KWC3_DERIVATION_CONFIG, } from '@dashlane/framework-services';
export type CryptoDerivationConfig = typeof DEFAULT_FLEXIBLE_ARGON2D_DERIVATION_CONFIG | typeof DEFAULT_FLEXIBLE_PBKDF2_DERIVATION_CONFIG | typeof DEFAULT_NODERIVATION_CONFIG | typeof KWC3_DERIVATION_CONFIG;
